apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: batchivo
  namespace: batchivo
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`batchivo.app`) && PathPrefix(`/api`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`batchivo.app`) && PathPrefix(`/uploads`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`batchivo.app`)
    priority: 1
    services:
    - name: frontend
      port: 8080
  - kind: Rule
    match: Host(`www.batchivo.app`) && PathPrefix(`/api`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`www.batchivo.app`) && PathPrefix(`/uploads`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`www.batchivo.app`)
    priority: 1
    services:
    - name: frontend
      port: 8080
