apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nozzly
  namespace: nozzly
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`nozzly.app`) && PathPrefix(`/api`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`nozzly.app`) && PathPrefix(`/uploads`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`nozzly.app`)
    priority: 1
    services:
    - name: frontend
      port: 8080
  - kind: Rule
    match: Host(`www.nozzly.app`) && PathPrefix(`/api`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`www.nozzly.app`) && PathPrefix(`/uploads`)
    priority: 100
    services:
    - name: backend
      port: 8000
  - kind: Rule
    match: Host(`www.nozzly.app`)
    priority: 1
    services:
    - name: frontend
      port: 8080
